/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControleAlunoSelMonitoria;
import controller.ControleMonitorSelSala;
import exception.DAOException;
import java.awt.Color;
import java.net.URL;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import model.Monitor;
import model.MonitoriaNBD;
import model.Sala;
import util.Alert;

/**
 *
 * @author snow
 */
public class ViewMonitorSelecaoSala extends javax.swing.JFrame {

    Monitor monitor;
    List<Sala> salas;
    ControleMonitorSelSala ctrlMntorSelSala;
    ControleAlunoSelMonitoria ctrlAlunoSelMonitoria;
    ViewMonitorSelDispTM tableModel1;
    ViewMonitorSelPossuiTM tableModel2;

    public ViewMonitorSelecaoSala(Monitor mon) {
        initComponents();
        this.monitor = mon;
        labelNomeMonitor.setText(monitor.getNome());
        URL iconURL = getClass().getResource("/img/clock4.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
    }

    public void setDataSet(List<Sala> salas) {
        tableModel1 = new ViewMonitorSelDispTM(salas);
        tbHorDisponivel.setModel(tableModel1);//vazio
        tableModel2 = new ViewMonitorSelPossuiTM(salas);
        tbHorMonitor.setModel(tableModel2);//vazio
        this.salas = salas;//fill monitorias
    }

    public void updateView() throws SQLException, DAOException {
        this.salas = ctrlMntorSelSala.getAllData();
        tableModel1.refresh(this.salas);
        tableModel2.refresh(this.salas, monitor.getNome());
        if (tableModel2.getRowCount() == 1) {
            lbTempoGasto.setText("Tempo dedicado a monitoria: " + tableModel2.getRowCount() + " hora.");
        } else {
            lbTempoGasto.setText("Tempo dedicado a monitoria: " + tableModel2.getRowCount() + " horas.");
        }
        if (tableModel2.getRowCount() < 6) {
            lbTempoGasto.setForeground(Color.red);
            Alert.aviso("Voce esta abaixo do tempo minimo de 6 horas por semana.");
        } else {
            lbTempoGasto.setForeground(Color.green);
        }
    }

    public void setController(ControleMonitorSelSala controleMonitorSelSala) {
        this.ctrlMntorSelSala = controleMonitorSelSala;
        this.ctrlAlunoSelMonitoria = new ControleAlunoSelMonitoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHorDisponivel = new javax.swing.JTable();
        btSelecionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbHorMonitor = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelNomeMonitor = new javax.swing.JLabel();
        btRemover = new javax.swing.JButton();
        lbTempoGasto = new javax.swing.JLabel();
        btVerLotacao = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MoniTime | Seleção de Salas");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbHorDisponivel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbHorDisponivel);

        btSelecionar.setText("Adicionar Horário");
        btSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSelecionarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SALAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(358, 358, 358)
                            .addComponent(btSelecionar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSelecionar)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbHorMonitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbHorMonitor);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("MEUS HORÁRIOS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Monitor: ");

        labelNomeMonitor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNomeMonitor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btRemover.setText("Remover Horário");
        btRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRemoverMouseClicked(evt);
            }
        });

        lbTempoGasto.setText("Tempo gasto em monitorias");

        btVerLotacao.setText("Lotaçao");
        btVerLotacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVerLotacaoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNomeMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lbTempoGasto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btVerLotacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemover)
                        .addGap(13, 13, 13))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(labelNomeMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTempoGasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVerLotacao)
                    .addComponent(btRemover))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSelecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionarMouseClicked
        try {
            if (tbHorDisponivel.getSelectedRow() > -1) {
                Sala sl = salas.get(tbHorDisponivel.getSelectedRow());
                if (sl.getOcupacao().equals("livre")) {
                    ctrlMntorSelSala.atualizaOcupacao(sl, monitor.getNome());
                    MonitoriaNBD moniF = new MonitoriaNBD(monitor, sl);
                    ctrlAlunoSelMonitoria.addMonitoria(moniF);
                    updateView();
                } else {
                    Alert.aviso("Selecione uma sala livre.");
                }
            } else {
                Alert.aviso("Selecione um horario na tabela.");
            }
        } catch (DAOException | SQLException ex) {
            Logger.getLogger(ViewMonitorSelecaoSala.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSelecionarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoverMouseClicked
        try {
            if (tbHorMonitor.getSelectedRow() > -1) {
                Sala sl = tableModel2.getSalas().get(tbHorMonitor.getSelectedRow());
                ctrlMntorSelSala.atualizaOcupacao(sl, "livre");
                MonitoriaNBD moniF = new MonitoriaNBD(monitor, sl);
                ctrlAlunoSelMonitoria.delMonitoriaProc(moniF);
                updateView();
            } else {
                Alert.aviso("Selecione um horario na tabela.");
            }
        } catch (DAOException | SQLException ex) {
            Logger.getLogger(ViewMonitorSelecaoSala.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRemoverMouseClicked

    private void btVerLotacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVerLotacaoMouseClicked
        if (tbHorMonitor.getSelectedRow() > -1) {
            Sala sl = tableModel2.getSalas().get(tbHorMonitor.getSelectedRow());
            MonitoriaNBD moniF = new MonitoriaNBD(monitor, sl);
            try {
                ;
                ViewVerLotacao verLot = new ViewVerLotacao(ctrlAlunoSelMonitoria.lotMonitoria(moniF));
                verLot.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                verLot.setLocationRelativeTo(null);
                verLot.setVisible(true);
            } catch (DAOException | SQLException ex) {
                Logger.getLogger(ViewMonitorSelecaoSala.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btVerLotacaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ViewMonitorSelecaoSala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JButton btVerLotacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNomeMonitor;
    private javax.swing.JLabel lbTempoGasto;
    private javax.swing.JTable tbHorDisponivel;
    private javax.swing.JTable tbHorMonitor;
    // End of variables declaration//GEN-END:variables
}
