/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControleCadMonitor;
import controller.ControleCadSala;
import controller.ControleRelatorios;
import exception.DAOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import model.Usuario;
import util.Alert;

/**
 *
 * @author snow
 */
public class ViewOpcoesCoordenador extends javax.swing.JFrame {
    
    Usuario usuario;
    
    public ViewOpcoesCoordenador(Usuario usuario) {
        initComponents();
        URL iconURL = getClass().getResource("/img/clock4.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        this.usuario = usuario;
        lbCoordenador.setText("Coordenador: " + usuario.getNome());
        //Alert.aviso(usuario.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadMonitores = new javax.swing.JButton();
        btCadSalas = new javax.swing.JButton();
        btRelatorios = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        lbCoordenador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monitime | Opções do Coordenador");

        btCadMonitores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCadMonitores.setText("CADASTRO DE MONITORES");
        btCadMonitores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadMonitoresMouseClicked(evt);
            }
        });

        btCadSalas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCadSalas.setText("CADASTRO DE SALAS");
        btCadSalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadSalasMouseClicked(evt);
            }
        });

        btRelatorios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRelatorios.setText("RELATÓRIOS");
        btRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRelatoriosMouseClicked(evt);
            }
        });

        btLogout.setText("Logout");
        btLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLogoutMouseClicked(evt);
            }
        });

        lbCoordenador.setText("Coordenador: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCadMonitores, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCadSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCoordenador))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbCoordenador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCadMonitores, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCadSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLogout)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadMonitoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadMonitoresMouseClicked
        ViewCadMonitor viewCadMonitor = new ViewCadMonitor(usuario);
        ControleCadMonitor controleCadMonitor = new ControleCadMonitor();
        try {
            viewCadMonitor.setDataSet(controleCadMonitor.getAllData());
            controleCadMonitor.setView(viewCadMonitor);
            viewCadMonitor.setController(controleCadMonitor);
            viewCadMonitor.updateView();
        } catch (DAOException | SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        viewCadMonitor.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        viewCadMonitor.setLocationRelativeTo(null);
        viewCadMonitor.setVisible(true);
    }//GEN-LAST:event_btCadMonitoresMouseClicked

    private void btCadSalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadSalasMouseClicked
        ViewCadSala viewCadSala = new ViewCadSala();
        ControleCadSala controleCadSala = new ControleCadSala();
        try {
            viewCadSala.setDataSet(controleCadSala.getAllData());
            viewCadSala.setController(controleCadSala);
            controleCadSala.setView(viewCadSala);
            viewCadSala.updateView();
        } catch (DAOException | SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        viewCadSala.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        viewCadSala.setLocationRelativeTo(null);
        viewCadSala.setVisible(true);
    }//GEN-LAST:event_btCadSalasMouseClicked

    private void btRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRelatoriosMouseClicked
        // TODO add your handling code here:
        ViewRelatorio viewRelat;
        try {
            viewRelat = new ViewRelatorio();
            ControleRelatorios controlRelat = new ControleRelatorios();
            viewRelat.setController(controlRelat);
            controlRelat.setView(viewRelat);
            viewRelat.setLocationRelativeTo(null);
            viewRelat.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            viewRelat.setVisible(true);
        } catch (DAOException | SQLException ex) {
            Logger.getLogger(ViewOpcoesCoordenador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRelatoriosMouseClicked

    private void btLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogoutMouseClicked
        this.usuario = null;
        this.dispose();
        ViewLogin viewLogin;
        try {
            viewLogin = new ViewLogin();
            viewLogin.setLocationRelativeTo(null);
            viewLogin.setVisible(true);
        } catch (DAOException | SQLException ex) {
            Logger.getLogger(ViewAlunoSelMonitoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOpcoesCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOpcoesCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOpcoesCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOpcoesCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //     new ViewOpcoesMonitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadMonitores;
    private javax.swing.JButton btCadSalas;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btRelatorios;
    private javax.swing.JLabel lbCoordenador;
    // End of variables declaration//GEN-END:variables
}
